#!/usr/bin/with-contenv bash

# read credentials from environment
cat <<EOF >> /etc/openvpn/auth
${PIA_USER}
${PIA_PASSWORD}
EOF

# link region
rm -f /etc/openvpn/service.conf

# check if region file exists
if [ ! -e /etc/openvpn/${PIA_REGION}.ovpn ]; then 
	echo "Region file ${PIA_REGION}.ovpn does not exist!"
    exit 1
fi

# use region file as ovpn configuration
cp /etc/openvpn/${PIA_REGION}.ovpn /etc/openvpn/service.conf

sed -i '/dev tun/d' /etc/openvpn/service.conf
sed -i '/persist-tun/d' /etc/openvpn/service.conf
sed -i '/iproute/d' /etc/openvpn/service.conf

cat <<EOF >> /etc/openvpn/service.conf
iproute /usr/local/sbin/unpriv-ip
dev tun0
persist-tun
EOF

# create tun with righ tuser and group
openvpn --rmtun --dev tun0
openvpn --mktun --dev tun0 --dev-type tun --user openvpn --group openvpn