#!/usr/bin/with-contenv sh

echo "IP with INACTIVE vpn: `wget http://ipinfo.io/ip -qO -`"

iptables -A INPUT -i lo -j ACCEPT
iptables -A OUTPUT -o lo -j ACCEPT
iptables -A OUTPUT -d 255.255.255.255 -j ACCEPT
iptables -A INPUT -s 255.255.255.255 -j ACCEPT 
iptables -A INPUT -s 192.168.0.0/16 -d 192.168.0.0/16 -j ACCEPT
iptables -A OUTPUT -s 192.168.0.0/16 -d 192.168.0.0/16 -j ACCEPT
iptables -A FORWARD -i eth+ -o tun+ -j ACCEPT
iptables -A FORWARD -i tun+ -o eth+ -j ACCEPT 
iptables -t nat -A POSTROUTING -o tun+ -j MASQUERADE 
iptables -A OUTPUT -o eth+ ! -d a.b.c.d -j DROP


openvpn --cd /etc/openvpn --config service.conf --auth-nocache

echo "IP with ACTIVE vpn: `wget http://ipinfo.io/ip -qO -`"